## Array fundamentals

In [41]:
 #Creating Numpy 1D Array
import numpy as np
a = np.array([10,22,53,34,15])
print("1D array :",a)
b = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
print("2D array :")
print(b)
#Shape of Array
np.shape(b)

1D array : [10 22 53 34 15]
2D array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [19]:
a[3]

34

In [21]:
a[2:4]

array([53, 34])

In [24]:
a[2:]

array([53, 34, 15])

In [26]:
a[1] = 23
a

array([10, 23, 53, 34, 15])

In [40]:
d = np.array([[43,65,23,67,88],[32,45,76,33,78],[21,90,9,6,45],[43,65,87,35,53]])
print(d)
print(d[2,2])
print(d[1,3])

[[43 65 23 67 88]
 [32 45 76 33 78]
 [21 90  9  6 45]
 [43 65 87 35 53]]
9
33


## Array attributes
1)ndim <br>
2)shape <br>
3)size <br>
4)dtype <br>

In [43]:
#ndim
a.ndim

1

In [44]:
b.ndim

2

In [45]:
d.ndim

2

In [46]:
#shape = number of elements along each dimension.
d.shape

(4, 5)

In [47]:
#size = total number of elements in array
d.size

20

In [48]:
#dtype = datatype of element of array
d.dtype

dtype('int32')

In [49]:
c = np.array([1,2,3,4],dtype=float)
print(c)

[1. 2. 3. 4.]


In [61]:
e = np.array([15,62,34,4],dtype = np.int64)
print(e.dtype)

int64


In [93]:
#ndim
a1 = np.arange(1,13)
a2 = np.arange(1,13).reshape(3,4)
a3 = np.arange(1,9).reshape(2,2,2)
print("Dimention of Array",a1.ndim)
print("Dimention of Array",a2.ndim)
print("Dimention of Array",a3.ndim)

#shape
print("Shape of Array",a1.shape)
print("Shape of Array",a2.shape)
print("Shape of Array",a3.shape)

#size
print("Size of Array",a1.size)
print("Size of Array",a2.size)
print("Size of Array",a3.size)


Dimention of Array 1
Dimention of Array 2
Dimention of Array 3
Shape of Array (12,)
Shape of Array (3, 4)
Shape of Array (2, 2, 2)
Size of Array 12
Size of Array 12
Size of Array 8


## How to create a basic array
1)np.zeros <br>
2)np.ones <br>
3)np.empty <br>
4)np.identity <br>
5)np.arange <br>
6)np.linspace

In [52]:
#np.zeros() =  create an array filled with 0’s:
a1 = np.zeros((3,4))
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
#np.ones() =  create an array filled with 1’s:
b1 = np.ones((3,4))
b1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
c1  =np.empty((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [144]:
#np.identity 
#Creating identity matrix
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [55]:
#np.arange() = create an array with a range of elements
#(Starting piont,Ending point,Jumping point)
a = np.arange(1,11)
print("Array From 1-10")
print(a)
b = np.arange(1,10,2)
print("Array Fromm 1-10 With 2 Point Defference")
print(b)


Array From 1-10
[ 1  2  3  4  5  6  7  8  9 10]
Array Fromm 1-10 With 2 Point Defference
[1 3 5 7 9]


In [58]:
#np.linspace = create an array with values that are spaced linearly in a specified interval
c = np.linspace(0,10,5)
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Adding, removing, and sorting elements

In [63]:
#sort = sort the numbers in ascending order with
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
#concatenate = merge two array into single array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
x = np.array([[1,5,3,6],
             [7,4,2,7]])
y = np.array([[4,2,7,5]])
np.concatenate((x,y))

array([[1, 5, 3, 6],
       [7, 4, 2, 7],
       [4, 2, 7, 5]])

## Can you reshape an array?

In [72]:
#reshape
#Covert Array into matrix form
a = np.arange(1,13)
print(a)
b = a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## How to convert a 1D array into a 2D array (how to add a new axis to an array)? 
1)np.newaxis <br>
2)np.expand_ndims

In [80]:
# np.newaxis = will increase the dimensions of your array by one dimension when used once.
a = np.array([1,2,3,5,8])
print("1D array",a.shape)

1D array (5,)


In [81]:
a2 = a[np.newaxis,:]
print("2D array",a2.shape)

2D array (1, 5)


In [82]:
a3 = a2[np.newaxis,:]
print("3D array",a3.shape)

3D array (1, 1, 5)


In [90]:
#np.expand_ndims 
b = np.array([2,4,5,7,2,8,6])
b1 = np.expand_dims(b , axis=0)
print(b)
b1.shape

[2 4 5 7 2 8 6]


(1, 7)

In [91]:
b2 = np.expand_dims(b , axis=1)
print(b2)
b2.shape

[[2]
 [4]
 [5]
 [7]
 [2]
 [8]
 [6]]


(7, 1)

## slicing

In [92]:
#idexing 
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a1[3])#colum
print(a2)
print(a2[1,2])#[row,colum]
print(a3)
print(a3[1,0,1])#[2D aaray,row,colum]

[0 1 2 3 4 5 6 7 8 9]
3
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5


In [94]:
#2D array Slicing
a1 = np.arange(1,11)
a2 = np.arange(12).reshape(3,4)
print(a1)
print(a1[5:9])
print("2D arrray\n",a2)
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3])
print(a2[::2,::3])

[ 1  2  3  4  5  6  7  8  9 10]
[6 7 8 9]
2D arrray
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]


In [95]:
#3D array Slicing
a3 = np.arange(27).reshape(3,3,3)
print("3D array\n",a3)
print("Middle Array\n",a3[1])
print("Alternative array\n",a3[::2])
print(" \n",a3[0,1,:])
print(" \n",a3[1,2,1:2])
print(" \n",a3[2,1:,1:])

3D array
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Middle Array
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Alternative array
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
 
 [3 4 5]
 
 [16]
 
 [[22 23]
 [25 26]]


In [97]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a > 5])

[ 6  7  8  9 10 11 12]


In [98]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## How to create an array from existing data
1)np.vstack() <br>
2)np.hstack() <br>
3)np.hsplit() <br>
4).view()

In [99]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [100]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
#np.hsplit = split array into equally split array
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [108]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [117]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x1 + x2

array([5, 7, 9])

In [118]:
x1-x2

array([-3, -3, -3])

In [119]:
x1*x2

array([ 4, 10, 18])

In [122]:
x2.sum()

15

## Broadcasting

In [138]:
#scalar operation
a1 = np.array([1,5,2,8,5,23,54,24])
print("Addition\n",a1+2)
print("Subtraction\n",a1-2)
print("Mutipliction\n",a1*2)
print("Divivsion\n",a1/2)
print("Power\n",a1**2)

Addition
 [ 3  7  4 10  7 25 56 26]
Subtraction
 [-1  3  0  6  3 21 52 22]
Mutipliction
 [  2  10   4  16  10  46 108  48]
Divivsion
 [ 0.5  2.5  1.   4.   2.5 11.5 27.  12. ]
Power
 [   1   25    4   64   25  529 2916  576]


In [139]:
#Vector Operation
#Operation between two array
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print("Addition\n",a1+a2)
print("Subtraction\n" ,a1-a2)
print("Multipliction\n",a1*a2)
print("Division\n",a1/a2)

Addition
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Subtraction
 [[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
Multipliction
 [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
Division
 [[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [141]:
#max/min/sum/product
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)
print("Maximum value in a1",np.max(a1)) #,axis=1(Row),#axis=0(Colum)
print("Minimum value in a1",np.min(a1))
print("Sum of All value of Colum of a1",np.sum(a1,axis=0))
print("Product of All value of a1",np.prod(a1,axis=1))

[[63. 11. 75.]
 [30. 56. 35.]
 [69. 98. 30.]]
Maximum value in a1 98.0
Minimum value in a1 11.0
Sum of All value of Colum of a1 [162. 165. 140.]
Product of All value of a1 [ 51975.  58800. 202860.]


In [140]:
#mean/median/std/var
a1 = np.random.random((3,3))
a1 = np.round(a1*50)
print(a1)
print("Mean of Matrix",np.mean(a1))
print("Median of Matrix",np.median(a1))
print("Standard Deviation",np.std(a1))
print("Variance",np.var(a1))

[[24. 38. 41.]
 [ 8. 19. 35.]
 [ 5. 30. 12.]]
Mean of Matrix 23.555555555555557
Median of Matrix 24.0
Standard Deviation 12.58845247846093
Variance 158.46913580246914


In [145]:
#dot product
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print("First matrix\n",a1)
print("Second matrix\n",a2)
print("Dot Product\n",np.dot(a1,a2))
print("Log of Every no.\n",np.log(a2))
print("Exponent of Every no.\n",np.exp(a2))

First matrix
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Second matrix
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Dot Product
 [[114 120 126]
 [378 400 422]
 [642 680 718]]
Log of Every no.
 [[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
Exponent of Every no.
 [[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


In [147]:
#round/floor/ceil
#round=roundoff the nearest integer
#floor=before integer
#ceil=after integer
a1 = np.round(np.random.random((2,3))*100)
a2 = np.floor(np.random.random((2,3))*100)
a3 = np.ceil(np.random.random((2,3))*100)
print(a1)
print(a2)
print(a3)


[[18.  1. 75.]
 [86. 97.  4.]]
[[71.  0. 77.]
 [67. 43. 57.]]
[[59. 54. 40.]
 [10. 76. 88.]]


## unique items

In [143]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Generating random numbers

In [135]:
#np.random
#Generate random array from 0-1 random number
a = np.random.random((3,4))
print(a)
#Random Value from 0-100
print("Random Value from 0-100")
b = np.random.random((5,5))
b = np.round(b*100)
print(b)

[[0.94105173 0.79039128 0.73155787 0.38693023]
 [0.00521289 0.11131401 0.78040431 0.41692409]
 [0.25009276 0.63166538 0.28387049 0.18330746]]
Random Value from 0-100
[[64. 74. 97. 42. 49.]
 [78. 35. 74.  2. 23.]
 [33. 22. 42. 38. 19.]
 [44. 95.  3. 37. 48.]
 [50.  3. 31. 20. 34.]]


## Transposing and reshaping a matrix

In [148]:
#Transpose
#Transpose Row into colum
a1 = np.arange(12).reshape(3,4)
print("2D Array\n",a1)
print("2D Transpose Array\n",np.transpose(a1))
#We can aslo use a1.T
print("2D Transpose Array\n",a1.T)

2D Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2D Transpose Array
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
2D Transpose Array
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [159]:
#reshape
data = np.arange(12).reshape(3,4)
print(data)
data.reshape(4,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## How to reverse an array

In [167]:
#np.flip() =  reverse the contents of an array along an axis.
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print("reversing 1D array",np.flip(arr))

[1 2 3 4 5 6 7 8]
reversing 1D array [8 7 6 5 4 3 2 1]


In [165]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print("reversing 2D array\n",np.flip(arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
reversing 2D array
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [169]:
# reverse only the rows
np.flip(arr1 , axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [170]:
#reverse only the column
np.flip(arr1 , axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

## Flattening multidimensional arrays

In [175]:
#.flatten = changes to your new array won’t change the parent array
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("original array\n",x)
x.flatten()

original array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [177]:
a1 = x.flatten()
a1[0] = 99
print("Original array\n",x)
print("New array\n",a1)

Original array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array
 [99  2  3  4  5  6  7  8  9 10 11 12]


In [180]:
#Ravel = the changes you make to the new array will affect the parent array
#Covert Multidimention Array into 1D Array
a2 = x.ravel()
a2[0] = 98
print("original array\n",x)
print("New array\n",a2)

original array
 [[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array
 [98  2  3  4  5  6  7  8  9 10 11 12]


## access the docstring for more information

In [183]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



## How to save and load NumPy objects

In [184]:
a = np.array([1, 2, 3, 4, 5, 6])
#np.save('filename', a)

In [ ]:
#np.savetxt('new_file.csv', a)